### ISSUE TITLE
Client-side routing for filters

### ISSUE THREAD

**Issue by kyle-n** [randomoscars/randomoscars.github.io#4]
Suggested by @RikBoeykens: As a user, when I set a category or year filter, it should persist after refresh.

---

We will implement this using client-side routing and adding a query param to the URL. That way, the user can go back, refresh or share their page of search results. 

Query params should be in the form of: `?category=1&year=2021` where the number next to the category is an ID associated to the category's `normalized_name`.

**Comment by kyle-n** [comment]
@RikBoeykens Would it be possible to update the JSON data with a `category_id` field that corresponds to the `normalized_name`? It would have to be done in some kind of automated way and I'm not the best at scripting.

**Comment by RikBoeykens** [comment]
created a pull request with the ids: https://github.com/randomoscars/randomoscars.github.io/pull/5
